[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.6.12"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.6.0"

[[constraint]]
  name = "github.com/hashicorp/nomad"
  version = "0.7.0"

[[constraint]]
  name = "github.com/hashicorp/raft"
  revision = "3a6f3bdfe4fc69e300c6d122b1a92051af6f0b95"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
